### ISSUE TITLE
Tentative Land Prep schedule - Blks 1 & 10 [January-May]

### ISSUE THREAD

**Issue by Danielcalza** [TREC-Agroecology/hemp-nutrition#2]
January
.
1/13-19 – Mowing. 
1/20-27 – Disc down mounds. 
.
February
. 
2/1-2/9 – Moldboard plow.
2/21-25 – Disc w/drag. 
.
March
.
3/1-3/4 – Leveling disks - as needed.
3/7-11 – Calibration run of the new planter, block 1. 
3/14-18 – Monitor germination/ re-test planter?
3/23-31 – Discing other plots as needed/weed control.
.
April
.
4/1-8 – Measure and mark plots and buffers.
4/11-4/15 – Final discing, bed, and mound shaping. 
4/25-29 – Drip irrigation and Bio-mulch for EO.
.
May
.
5/5 – Planting of EO-N, 'Maverick'.
5/5 – Apply N fertilizer at the time of planting, broadcasted.
5/6 – Transplanting 'Wife' and 'CBG-Gold'.
5/3-6 – Overhead irrigation for Grain and Fiber.
5/11 – Appy N fertilizer for Grain and Fiber.
5/12 – Planting of Grain and Fiber.
5/16-20 – Plant sorghum buffers.

**Comment by Danielcalza** [comment]
Hi everyone,  please review the schedule and feel free to make any corrections or comments. I am also sending it to Jose for review.

**Comment by Tamara729** [comment]
Hi Daniel, 
I made some changes to better match the 2021 growing season and I don't believe we're doing an early planting. 

4/25-29 – Setting out irrigation for essential oil
(time?) - Biodegradable plastic mulch applied to raised beds

May
5/5 - Planting of EO-N, 'Maverick'
5/5 – Apply N fertilizer at the time of planting, broadcasted
5/6 - Planting of EO-N, transplanting 'Wife' and 'CBG-Gold'

5/3-6 – Layout irrigation for Grain and Fiber N Study
5/11 – Appy N fertilizer one day before planting, broadcast by hand
5/12 – Planting of Grain and Fiber N Study

5/16-20 – Plant sorghum buffers.
